default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  <<: *default
  host: postgres
  user: postgres
  password: root

development:
  <<: *local
  database: figma_integration_api_development

test:
  <<: *local
  database: figma_integration_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
